<a href="https://colab.research.google.com/github/Devansh-react/PyTorch_fundamentals/blob/main/Ch01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Ch-01**

In [ ]:
import torch
print(torch.__version__)

2.9.0+cu126


In [ ]:
if torch.cuda.is_available():
  print(f"GPU available : {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available")


GPU available : Tesla T4


# Creating tensor

In [ ]:
# using empty->allocate memeory it did't itself assigins value but shows the value already present at that memeory location
a=torch.empty(2,3)
a.type()


'torch.FloatTensor'

In [ ]:
a=torch.zeros(2,3)
b=torch.ones(2,3)
a,b

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]))

In [ ]:
a=torch.rand(2,3)
a


tensor([[0.0406, 0.1111, 0.1444],
        [0.0454, 0.2709, 0.4435]])

In [ ]:
# to have reproduciblity while using the rand function we use seed means everytime we run rand it will return that same random value tensor
torch.manual_seed(100)
a=torch.rand(2,3)
a

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
a=torch.tensor([[1,2,3],[4,5,6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other methods

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace ->  10 linearly spaced values b/w 0 to 10 ;
print("using linspace ->", torch.linspace(0,10,10))
# using eye -> identity matrix
print("using eye ->",torch.eye(5))

# using full-> 3x3 tensor with every item is 5
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shape

In [ ]:
x= torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [ ]:
#  to create a tensor as same shape as some other tensor
y = torch.empty_like(x)
k = torch.zeros_like(x)
l = torch.ones_like(x)
g = torch.rand_like(x,dtype=torch.float64)
y,k,l,g

(tensor([[    139912115109264,     139912115109264,                   0],
         [                  0,        498216206336, 7310593858020254331]]),
 tensor([[0, 0, 0],
         [0, 0, 0]]),
 tensor([[1, 1, 1],
         [1, 1, 1]]),
 tensor([[0.1015, 0.6642, 0.9736],
         [0.6941, 0.3464, 0.9751]], dtype=torch.float64))

# Tensor datatypes

In [ ]:
x.dtype

torch.int64

In [ ]:
# assigning dtype
x = torch.tensor([1.0,2.0,3.0],dtype=torch.int64)
y = torch.tensor([10,20,30],dtype=torch.float16)
a.to(torch.int64)
x,y,a

(tensor([1, 2, 3]),
 tensor([10., 20., 30.], dtype=torch.float16),
 tensor([[1, 2, 3],
         [4, 5, 6]]))

# Mathematical operations

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [ ]:
# addition
print(x + 2)
# substraction
print(x - 2)
# multiplication
print(x * 3)
# division
print(x / 3)
# int division
print((x * 100)//3)
# mod
print(((x * 100)//3)%2)
# power
print(x**2)

tensor([[2.2239, 2.3023],
        [2.1784, 2.8238]])
tensor([[-1.7761, -1.6977],
        [-1.8216, -1.1762]])
tensor([[0.6717, 0.9070],
        [0.5353, 2.4715]])
tensor([[0.0746, 0.1008],
        [0.0595, 0.2746]])
tensor([[ 7., 10.],
        [ 5., 27.]])
tensor([[1., 0.],
        [1., 1.]])
tensor([[0.0501, 0.0914],
        [0.0318, 0.6787]])


Elementwise operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])
tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])


In [ ]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** b)
print(a % b)

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])
tensor([[ 0.3132,  0.2767, -0.0837],
        [ 0.7007, -0.0464,  0.0657]])
tensor([[0.1348, 0.6842, 0.2343],
        [0.2343, 0.5888, 0.2072]])
tensor([[2.2912, 1.3951, 0.8415],
        [3.8346, 0.9413, 1.1552]])
tensor([[0.8672, 0.9839, 0.6515],
        [0.9868, 0.7919, 0.7388]])
tensor([[0.0706, 0.2767, 0.4440],
        [0.2063, 0.7445, 0.0657]])


In [ ]:
c = torch.tensor([-1.111,0.29929292,3.9999,-4.1290])
c

tensor([-1.1110,  0.2993,  3.9999, -4.1290])

In [ ]:
print(c.abs())
print(c.neg())
print(c.round())
print(c.ceil())
print(c.floor())
print(c.clamp(min=0,max=3))

tensor([1.1110, 0.2993, 3.9999, 4.1290])
tensor([ 1.1110, -0.2993, -3.9999,  4.1290])
tensor([-1.,  0.,  4., -4.])
tensor([-1.,  1.,  4., -4.])
tensor([-2.,  0.,  3., -5.])
tensor([0.0000, 0.2993, 3.0000, 0.0000])


In [ ]:
e = torch.randint(size=(2,3),low=7,high=10,dtype=torch.float32)
e

tensor([[9., 7., 7.],
        [7., 9., 9.]])

In [ ]:
print(torch.sum(e))
# sum along col
print(torch.sum(e,dim=0))
print(torch.sum(e,dim=1))
print(torch.mean(e,dim=0))
print(torch.mean(e,dim=1))
print(torch.median(e,dim=0))
print(torch.min(e))
print(torch.std(e))
print(torch.var(e))

#  tell the position of max/min element
print(torch.argmax(e))
print(torch.argmin(e))

tensor(48.)
tensor([16., 16., 16.])
tensor([23., 25.])
tensor([8., 8., 8.])
tensor([7.6667, 8.3333])
torch.return_types.median(
values=tensor([7., 7., 7.]),
indices=tensor([1, 0, 0]))
tensor(7.)
tensor(1.0954)
tensor(1.2000)
tensor(0)
tensor(1)


In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 5],
        [9, 9, 7]])
tensor([[5, 9],
        [8, 9],
        [7, 9]])


In [ ]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[116, 153],
        [166, 225]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
torch.transpose(f,0,1)
# swaping the 0 with 1
# torch.det(g)

tensor([[5, 9],
        [7, 9],
        [5, 7]])

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[2, 6, 7],
        [7, 8, 3]])
tensor([[6, 1, 5],
        [5, 0, 4]])


In [ ]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

tensor([[True, True, True],
        [True, True, True]])

In [ ]:
k = torch.randint(size=(2,3), low=5, high=10, dtype=torch.float32)
k

tensor([[8., 8., 8.],
        [8., 8., 5.]])

In [ ]:
print(torch.sigmoid(k))
print(torch.softmax(k,dim=0))
print(torch.relu(k))

tensor([[0.9997, 0.9997, 0.9997],
        [0.9997, 0.9997, 0.9933]])
tensor([[0.5000, 0.5000, 0.9526],
        [0.5000, 0.5000, 0.0474]])
tensor([[8., 8., 8.],
        [8., 8., 5.]])


# Implace operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.9454, 0.7116, 0.1157],
        [0.6574, 0.3451, 0.0453]])
tensor([[0.9798, 0.5548, 0.6868],
        [0.4920, 0.0748, 0.9605]])


In [ ]:
m.add_(n)
m
m.relu_()

tensor([[4.8644, 2.9307, 2.8629],
        [2.6255, 0.6443, 3.8873]])

Copying a tennsor

In [ ]:
b=a.clone()

tensor on GPU

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
agpu = a.to(device)
agpu

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]], device='cuda:0')