<a href="https://colab.research.google.com/github/Devansh-react/PyTorch_fundamentals/blob/main/ch_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head(5)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df["diagnosis"].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [4]:
df.shape
df.drop(["Unnamed: 32","id"],axis=1,inplace=True)
df.head(5)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

Train/Test **Split**

In [5]:
X_train,X_test,Y_train,Y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

**Feature** **Scaling** / **Normalisation**

In [6]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train,X_test


(array([[-1.01552811,  1.35908731, -1.01228808, ..., -0.82645179,
          0.80255057, -0.13098267],
        [ 1.81668538,  1.95818749,  1.74629717, ...,  0.64117323,
         -0.75493092, -0.02942187],
        [-0.38072164, -1.39353513, -0.39691457, ...,  0.01046856,
         -0.84306002,  0.09682776],
        ...,
        [ 1.316883  ,  0.48241176,  1.26845818, ...,  1.39090794,
          1.23518432,  0.83580887],
        [-0.08198918, -0.63020285, -0.14137459, ..., -0.81315753,
         -0.3671629 , -0.3829208 ],
        [-1.32661201, -0.79443495, -1.33638757, ..., -0.65857305,
         -0.24217981, -0.11358828]]),
 array([[ 0.29717125,  2.60817648,  0.45820946, ...,  1.86702813,
          1.89214667,  3.20369066],
        [-0.30029367,  0.32280592, -0.26561273, ...,  0.05066053,
         -0.55303517, -0.11583272],
        [-1.12755278, -1.64797922, -1.10619383, ..., -0.73988449,
          0.04624268, -0.36945418],
        ...,
        [-0.38933892,  0.69059329, -0.2955296 , ...,  

In [7]:
Y_train

248    B
233    M
322    B
260    M
452    B
      ..
505    B
62     M
337    M
477    B
234    B
Name: diagnosis, Length: 455, dtype: object

**Lable** **Encoding**

In [8]:
encoder = LabelEncoder()
Y_train = encoder.fit_transform(Y_train)
Y_test = encoder.transform(Y_test)
Y_train,Y_test

(array([0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
        1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
        1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
        1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
        1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
        1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
        1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
        0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 

Converting **NumPy->Tensor**

In [9]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
Y_train_tensor = torch.from_numpy(Y_train).float()
Y_test_tensor = torch.from_numpy(Y_test).float()
X_train_tensor.shape,X_test_tensor.shape,Y_train_tensor.shape,Y_test_tensor.shape

(torch.Size([455, 30]),
 torch.Size([114, 30]),
 torch.Size([455]),
 torch.Size([114]))

# **Model pipeline **

In [11]:
class Trainig_class:
  def __init__(self,X):
    self.weights = torch.randn([X.shape[1],1],dtype =torch.float32, requires_grad = True)
    self.bais = torch.zeros(1,dtype = torch.float32, requires_grad = True)

  def forward(self,X):
    # X is now already float32, so no need for X.float()
    z = torch.matmul(X,self.weights)+ self.bais
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y_true):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_true * torch.log(y_pred) + (1 - y_true) * torch.log(1 - y_pred)).mean()
    return loss


#  paramneters
learning_rate = 0.001;
epochs = 25

In [12]:
model  = Trainig_class(X_train_tensor)

for epoch in range(epochs):

  # forward-pass
  y_pred = model.forward(X_train_tensor)
  #  loss function
  loss = model.loss_function(y_pred,Y_train_tensor)

  # backward_propogation
  loss.backward()

  #  parameter_update (using in-place operations)
  with torch.no_grad():
    model.weights.sub_(learning_rate * model.weights.grad)
    model.bais.sub_(learning_rate * model.bais.grad)

  #clearing gradient
  model.weights.grad.zero_()
  model.bais.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 2.6215198040008545
Epoch: 2, Loss: 2.620147228240967
Epoch: 3, Loss: 2.618795156478882
Epoch: 4, Loss: 2.617440938949585
Epoch: 5, Loss: 2.616091012954712
Epoch: 6, Loss: 2.6147396564483643
Epoch: 7, Loss: 2.6133062839508057
Epoch: 8, Loss: 2.611949920654297
Epoch: 9, Loss: 2.6106069087982178
Epoch: 10, Loss: 2.6092612743377686
Epoch: 11, Loss: 2.607910394668579
Epoch: 12, Loss: 2.6065468788146973
Epoch: 13, Loss: 2.6051383018493652
Epoch: 14, Loss: 2.603790044784546
Epoch: 15, Loss: 2.602433681488037
Epoch: 16, Loss: 2.6010632514953613
Epoch: 17, Loss: 2.5996766090393066
Epoch: 18, Loss: 2.5983123779296875
Epoch: 19, Loss: 2.596907615661621
Epoch: 20, Loss: 2.595545530319214
Epoch: 21, Loss: 2.5941760540008545
Epoch: 22, Loss: 2.592794418334961
Epoch: 23, Loss: 2.5914406776428223
Epoch: 24, Loss: 2.5900821685791016
Epoch: 25, Loss: 2.588669538497925


In [16]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == Y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5146198868751526
